# One of the DevOps team members has created a ZIP archive on jump host in 
# Stratos DC that needs to be extracted and copied over to all app servers 
# in Stratos DC itself. Because this is a routine task, the Nautilus DevOps 
# team has suggested automating it. We can use Ansible since we have been 
# using it for other automating tasks. Below you can find more details about the task:

# We have an inventory file under /home/thor/ansible on jump host, 
# which should have all the app servers added already.

# There is a ZIP archive /usr/src/finance/datacenter.zip on jump host.

# Create a playbook.yml under /home/thor/ansible/ on jump host itself to perform the following tasks.


# Unzip /usr/src/finance/datacenter.zip archive in /opt/finance/ location on all app servers.

# Make sure the unzipped data must has the respective sudo user as their user and group owner, 
# i.e tony for app server 1, steve for app server 2, banner for app server 3.

# The extracted data permissions must be 0744

# Note: Validation will try to run playbook using 
# command ansible-playbook -i inventory playbook.yml 
# so please make sure playbook works this way, without passing any extra arguments.

# ansible all -a "ls -ltr /opt/sysops" -i inventory  <<< check file ecxist
# ansible-playbook  -i inventory playbook.yml
# ssh tony@stapp01 "ls -al /opt/security/"

- name: Task create archive and copy to host
  hosts: stapp01, stapp02, stapp03
  become: yes
  tasks:
    - name: copy file
      copy:
        src: /usr/src/finance/datacenter.zip
        dest: /opt/finance


    - name: As per the task create the archive file and set the owner
      unarchive:
        src:  /opt/finance/datacenter.zip
        dest: /opt/finance
        remote_src: True
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        mode: '0744'