#We are working on an application that will be deployed on multiple containers within a pod on Kubernetes cluster. 
#There is a requirement to share a volume among the containers to save some temporary data. 
#The Nautilus DevOps team is developing a similar template to replicate the scenario. 
#Below you can find more details about it.

#1.Create a pod named volume-share-datacenter.

#2.For first container, use image ubuntu with latest tag only and 
#remember to mention tag i.e ubuntu:latest, container should be named 
#as volume-container-datacenter-1, and run a command '/bin/bash', '-c' and 
#'sleep 10000'. Volume volume-share should be mounted at path /tmp/beta.

#3.For second container, use image ubuntu with latest tag only and 
#remember to mention tag i.e ubuntu:latest, container should be named 
#as volume-container-datacenter-2, and run a command '/bin/bash', 'c' and
# 'sleep 10000'. Volume volume-share should be mounted at path /tmp/cluster.

#4.Volumes to be named as volume-share and use emptyDir: { }.

#5.After creating pods, exec into the first container volume-container-datacenter-1, 
#and create a file beta.txt with content Welcome to xFusionCorp Industries! 
#under the mount path of first container i.e /tmp/beta.

#6.The file beta.txt should be present under the mounted path /tmp/cluster of 
#second container volume-container-datacenter-2 as they are using shared volumes.

#Note: The kubectl utility on jump_host has been configured to work with the kubernetes cluster.

#kubectl exec -it volume-share-nautilus -c volume-container-nautilus-1 -- /bin/bash

apiVersion: v1
kind: Pod
metadata:
  name: volume-share-nautilus
spec:
  containers:
  - name: volume-container-nautilus-1
    image: centos:latest
    command: ["/bin/bash","-c","sleep 10000"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/beta
 
  - name: volume-container-nautilus-2
    image: centos:latest
    command: ["/bin/bash","-c","sleep 10000"]
    volumeMounts:
    - name: volume-share
      mountPath: /tmp/games
  volumes:
  - name: volume-share
    emptyDir: {}



